### ISSUE TITLE
async-h1 server example crash

### ISSUE THREAD

**Issue by zethra** [stjepang/smol#62]
I was playing around with the async-h1 server example and found that if the client process dies mid connection it kill the executor with this error.  This is from running single threaded, where the process exists after this.  If it's run multi threaded like in the example that executor thread dies.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connection reset by peer (os error 104)', /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/task.rs:162:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: core::result::Result<T,E>::unwrap
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/result.rs:1003
  15: smol::task::Task<core::result::Result<T,E>>::unwrap::{{closure}}
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/task.rs:162
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/future.rs:44
  17: async_task::raw::RawTask<F,R,S,T>::run
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-3.0.0/src/raw.rs:502
  18: async_task::task::Task<T>::run
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-3.0.0/src/task.rs:265
  19: smol::work_stealing::Worker::execute::{{closure}}
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/work_stealing.rs:176
  20: scoped_tls_hkt::ScopedKey<T>::set
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:488
  21: smol::throttle::setup
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/throttle.rs:31
  22: smol::work_stealing::Worker::execute
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/work_stealing.rs:176
  23: smol::run::run::{{closure}}
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/run.rs:150
  24: core::ops::function::FnOnce::call_once
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/ops/function.rs:232
  25: smol::context::enter
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/context.rs:8
  26: smol::run::run::{{closure}}::{{closure}}
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/run.rs:111
  27: scoped_tls_hkt::ScopedKey<T>::set
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:488
  28: smol::thread_local::ThreadLocalExecutor::enter
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/thread_local.rs:57
  29: smol::run::run::{{closure}}
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/run.rs:111
  30: smol::run::run::{{closure}}::{{closure}}
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/run.rs:112
  31: smol::work_stealing::WORKER::<impl smol::work_stealing::WORKER>::set
             at ./<::scoped_tls_hkt::scoped_thread_local macros>:40
  32: smol::work_stealing::Worker::enter
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/work_stealing.rs:149
  33: smol::run::run::{{closure}}
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/run.rs:112
  34: smol::run::run
             at /home/zethra/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.4/src/run.rs:114
  35: servy::main
             at src/main.rs:74
  36: std::rt::lang_start::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  37: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  38: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  40: std::panicking::try
             at src/libstd/panicking.rs:281
  41: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  42: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  43: std::rt::lang_start
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  44: main
  45: __libc_start_main
  46: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Running in Linux x86_64

Edit: I copied that example into a project named `servy`, that's why that name is in there.

**Comment by hwchen** [comment]
Can you give exact steps to reproduce? I tried introducing a delay into the `serve` fn so that I could manually disconnect the client, but that didn't kill any server processes.

**Comment by zethra** [comment]
I was testing it with the http benchmarking tool [wrk](https://github.com/wg/wrk).  So you run the example and run `wrk -c 1 -d 1 -t 1 http://127.0.0.1:8000/`.  For reference, here is the exact code I'm running https://github.com/zethra/servy/blob/v2/src/main.rs

**Comment by hwchen** [comment]
hmmm... I'm still unable to reproduce using your setup. How are you introducing the disconnect?

**Comment by zethra** [comment]
I let wrk run and the server panics, that's it.

**Comment by stjepang** [comment]
@zethra Can you verify whether https://github.com/stjepang/smol/pull/66 fixes the problem?

**Comment by zethra** [comment]
@stjepang that fixed it! For some reason I missed the unwrap on line 73.  Thanks!
